apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: c78rptnvp-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: c78rptnvp-nodejs 
  name: c78rptnvp-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: c78rptnvp-nodejs 
